# Replace the text below to customize your site
site_name: Heba Elidrisi
site_description: Master in Design for Emergent Futures
site_author: Heba Elidrisi
copyright: ""
repo_name: 'Name : Github Repo'
site_url: https://hebaelidrisi.github.io/mdef/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:
  - Home: index.md
  - Term 1:
      - Design Studio I: projects/design-studio-i.md
      - Living with your own ideas: reflections/living-with-your-own-ideas.md
      - Unpacking Tech Systems: reflections/unpacking-tech-systems.md
      - Atlas of Weak Signals: reflections/atlas-of-weak-signals.md
      - Fundamentals for Future Makers: reflections/fundamentals-for-future-makers.md
      - Narratives I: reflections/narratives-i.md
  - Term 2:
      - Design Studio II: projects/design-studio-ii.md
      - Extended Intelligences II: term2/extended-intelligences-ii.md
      - Cognitive Orgies: term2/cognitive-orgies.md
  - About: about/me.md
  - Contact: contact.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/hebaelidrisi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hebaelidrisi/
    - icon: fontawesome/brands/whatsapp
      link: "https://wa.me/your-phone-number"

theme:
  name: material
  logo: images/smallstoneedited.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes  # Add this to help the theme handle nested folders
    - hide.generator
  favicon: images/smallstoneedited.png
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: white
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono


plugins:
  - search:
      enabled: false
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
